## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [12]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [15]:
# Type your solution here
import pandas as pd
#Q1-1
df = pd.DataFrame(data)
print(df)
print()

#Q1-2
df2 = df[((df["job"] == "teacher") | (df["job"] == "psychologist")) & (df["num_cars"] > df["family_size"])]
print(df2)
print()

#Q1-3
df3 = df[(df["family_size"] < 4) & (df["num_cars"] >= 1)]
print(df3)

#Q1-4
print()
print(len(pd.unique(df["job"])), "unique jobs")

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1

   name           job  family_size  num_cars
5  Lisa  psychologist            3         4

     name             job  family_size  num_cars
0  Joseph         teacher            3         3
1   Jacob    psychologist            2         1
2     Sam  data scientist            1         1
4    Ryan    psychologist            2         2
5    Lisa    psychologist            3         4
6     Lee         teacher            2         1

4 unique jobs


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [47]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [49]:
# Type your solution here
print(fruit)
print(weights)

for i in np.unique(fruit.values):
  print(i, "mean weight: ", np.mean(weights[fruit[fruit==i].index]))


0     apple
1    carrot
2    carrot
3    carrot
4    banana
5     apple
6    carrot
7    banana
8    carrot
9    banana
dtype: object
0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
dtype: float64
apple mean weight:  3.5
banana mean weight:  7.666666666666667
carrot mean weight:  5.0


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [33]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [34]:
# Type your solution here
#Q3-1
print(course_name)
print(np.sort(course_name), "\n")


#Q3-2
print(course_name[np.char.endswith(course_name, "P", start=0, end=1)])
#print(course_name[np.char.find(course_name, "P", start=0, end=1)+1])
#print(course_name[course_name.index(0) == "Python"])

['Python' 'JS' 'examples' 'PHP' 'html']
['JS' 'PHP' 'Python' 'examples' 'html'] 

['Python' 'PHP']


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [35]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [36]:
# Type your solution here
#Q4-1
reversed = np.flip(student_id)
print(student_id)
print(reversed, "\n")

#Q4-2
print((np.sort(student_id))[-3:])

[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023] 

[5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [37]:
# Type your solution here
# Hint: you can use arange to start off
s = np.arange(100);
np.sum((s[(s%3 == 0) | (s%5 == 0)]))

2318

**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [38]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
# Type your solution here
#Q6-1
arr[0:, [0,1]] = arr[0:, [1,0]]
print(arr)
print()
#Q6-2
arr[[0, 1]] = arr[[1, 0]]
print(arr)

[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]

[[ 5  4  6  7]
 [ 1  0  2  3]
 [ 9  8 10 11]]
